# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d4dddfa1c32e0abb884f3f7c8a0b4784bbe811666c1006aeae51793e84df90c2d67e2b53a1803b15b374c6985224947d9e0cc80de6cf031e991453fc7085c00d

test:
  secret_key_base: 8adf4f7a5928fff63519033b6cdfeea2d045efee77d1a2284a03c054c41101de836a8feade288b3b63c220af4df1f893c8cf607366cbb87887d9c5cc6be0e552

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
